###
# This is example docker compose that sets up local developer environment.
# Please refer to README.md for instructions on how to run it.
###

version: "2.2"

services:
  schema_registry:
    image: cdl-schema-registry:latest
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        - BIN=schema-registry
        - ENV=DEV
    command: /bin/schema-registry
    ports:
      - "50101:50101"
    environment:
      DB_NAME: "/var/data/schema"
      REPLICATION_ROLE: "master"
      COMMUNICATION_METHOD: "amqp"
      AMQP_CONNECTION_STRING: "amqp://user:CHANGEME@rabbitmq:5672/%2f"
      AMQP_CONSUMER_TAG: "schema_registry"
      REPLICATION_SOURCE: "cdl.schema_registry.internal"
      REPLICATION_DESTINATION: "cdl.schema_registry.internal"
      INPUT_PORT: "50101"
      IMPORT_FILE: "/var/data/schema.json"
      RUST_LOG: info,schema_registry=trace
    volumes:
      - ./setup/schema_registry/initial-schema.json:/var/data/schema.json

  data_router:
    image: cdl-data-router:latest
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        - BIN=data-router
        - ENV=DEV
    command: /bin/data-router
    environment:
      COMMUNICATION_METHOD: "amqp"
      AMQP_CONNECTION_STRING: "amqp://user:CHANGEME@rabbitmq:5672/%2f"
      AMQP_CONSUMER_TAG: "data_router"
      INPUT_SOURCE: "cdl.data.input"
      SCHEMA_REGISTRY_ADDR: "http://schema_registry:50101"
      CACHE_CAPACITY: "1000"
      RUST_LOG: info,data_router=trace

  query_router:
    image: cdl-query-router:latest
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        - BIN=query-router
        - ENV=DEV
    command: "/bin/query-router"
    ports:
      - "50103:50103"
    environment:
      CACHE_CAPACITY: 1024
      INPUT_PORT: 50103
      SCHEMA_REGISTRY_ADDR: "http://schema_registry:50101"
      RUST_LOG: info,query_router=trace

  edge_registry:
    image: cdl-edge-registry:latest
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        - BIN=edge-registry
        - ENV=DEV
    command: "/bin/edge-registry"
    ports:
      - "50110:50110"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DBNAME: postgres
      POSTGRES_SCHEMA: cdl
      COMMUNICATION_PORT: 50110
      METHOD: amqp
      MQ_HOST: "amqp://user:CHANGEME@rabbitmq:5672/%2f"
      MQ_TAG: edge-registry
      MQ_SOURCE: "cdl.edge.input"
      RUST_LOG: info,edge_registry=trace

  web_api:
    image: cdl-api:latest
    command: "/bin/api"
    ports:
      - "50104:50104"
    build:
      context: ../..
      dockerfile: Dockerfile
      args:
        - BIN=api
    environment:
      INPUT_PORT: 50106
      RUST_LOG: info,api=trace
      SCHEMA_REGISTRY_ADDR: "http://schema_registry:50101"
      QUERY_ROUTER_ADDR: "http://query_router:50103"
      COMMUNICATION_METHOD: "amqp"
      AMQP_CONNECTION_STRING: "amqp://user:CHANGEME@rabbitmq:5672/%2f"
      AMQP_CONSUMER_TAG: "cdl-api"
      REPORT_SOURCE: "cdl.reports"
      INSERT_DESTINATION: "cdl.reports"

networks:
  compose_default:
    external: true
