apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-leader-elector-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-leader-elector-cr
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-leader-elector-rb
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-leader-elector-sa
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-leader-elector-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-leader-elector
  labels:
    app: {{ .Release.Name }}-leader-elector
spec:
  replicas: 1 # do not scale
  selector:
    matchLabels:
      app: {{ .Release.Name }}-leader-elector
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-leader-elector
    spec:
      serviceAccountName: {{ .Release.Name }}-leader-elector-sa
      containers:
      - name: cdl-leader-elector
        image: "{{ .Values.global.imageRepositoryPath }}cdl-leader-elector:{{ .Values.global.imageVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/leader-elector"]
        env:
        - name: HEARTBEAT_SECS
          value: "{{ .Values.leaderElector.heartbeatTime }}"
        - name: SCHEMA_APP_NAME
          value: "{{ .Release.Name }}-schema-registry"
        - name: SCHEMA_ADDR
          value: "http://{{ .Release.Name }}-schema-registry"
        - name: SCHEMA_PORT
          value: "6400"
        - name: RUST_LOG
          value: "info,leader-elector=debug"
      imagePullSecrets:
        - name: {{ .Values.global.cdlImagePullSecrets }}
