apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-object-builder
  labels:
    app: {{ .Release.Name }}-object-builder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-object-builder
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-object-builder
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '51805'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - name: cdl-object-builder
          image: "{{ .Values.global.imageRepositoryPath }}cdl-object-builder:{{ .Values.global.imageVersion }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["/bin/object-builder"]
          env:
            - name: OBJECT_BUILDER_INPUT_PORT
              value: "{{ .Values.objectBuilder.inputPort }}"
            - name: OBJECT_BUILDER_CHUNK_CAPACITY
              value: "128"
            {{- if eq .Values.global.communicationMethod "kafka" }}
            - name: OBJECT_BUILDER_COMMUNICATION_METHOD
              value: 'kafka'
            - name: OBJECT_BUILDER_KAFKA__BROKERS
              value: {{ .Values.global.kafkaBrokers }}
            - name: OBJECT_BUILDER_KAFKA__GROUP_ID
              value: "object-builder"
            - name: OBJECT_BUILDER_KAFKA__INGEST_TOPIC
              value: {{ .Values.global.objectBuilderInput }}
            {{- else if eq .Values.global.communicationMethod "amqp" }}
            - name: OBJECT_BUILDER_COMMUNICATION_METHOD
              value: 'amqp'
            - name: OBJECT_BUILDER_AMQP__EXCHANGE_URL
              value: {{ .Values.global.amqpConnectionString }}
            - name: OBJECT_BUILDER_AMQP__TAG
              value: "object-builder"
            - name: OBJECT_BUILDER_AMQP__INGEST_QUEUE
              value: {{ .Values.global.objectBuilderInput }}
            {{- end }}
            - name: OBJECT_BUILDER_SERVICES__SCHEMA_REGISTRY_URL
              value: "http://{{ .Release.Name }}-schema-registry:6400"
            - name: OBJECT_BUILDER_LOG__RUST_LOG
              value: "info,object_builder=debug"
            - name: OBJECT_BUILDER_MONITORING__OTEL_SERVICE_NAME
              value: "object-builder"
          ports:
            - containerPort: 51805
      imagePullSecrets:
        - name: {{ .Values.global.cdlImagePullSecrets }}
