[package]
name = "materializer-general"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace
rpc         = { path = "../rpc" }
utils       = { path = "../utils" }

# Crates.io
anyhow      = "1.0"
async-trait = "0.1"
clap        = "3.0.0-beta.2"
futures     = "0.3"
itertools   = "0.10"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
tokio       = { version = "1.5", features = ["rt-multi-thread", "macros", "sync"] }
tonic       = "0.4"
tracing     = "0.1"
uuid        = "0.8"
bb8-postgres            = { version = "0.7", features = ["with-uuid-0_8", "with-serde_json-1"] }
tracing-futures         = "0.2"
