[package]
name = "tracing_utils"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
grpc = ["tonic", "hyper", "opentelemetry-http"]
kafka = ["rdkafka"]
http = ["warp", "reqwest", "hyper", "tower-service", "opentelemetry-http"]

[dependencies]
anyhow      = "1.0"
hyper       = { version = "0.14", optional = true }
rdkafka     = { version = "0.26", features = ["cmake-build"], optional = true }
reqwest     = { version = "0.11", features = ["json"], optional = true }
tokio       = { version = "1.6", features = ["rt-multi-thread"] }
tracing     = "0.1"
warp        = { version = "0.3", optional = true }
futures-util            = "0.3"
opentelemetry           = {version = "0.13", features = ["rt-tokio"] }
opentelemetry-http      = { version = "0.2", optional = true }
opentelemetry-jaeger    = {version = "0.12", features = ["tokio"] }
tonic                   = { version = "0.4", optional = true }
tower-service           = { version = "0.3", optional = true }
tracing-futures         = "0.2"
tracing-opentelemetry   = "0.12"
tracing-subscriber      = "0.2"
