rabbitmq:
  replicaCount: 1
  service:
    type: NodePort
  extraSecrets:
    load-definition:
      load_definition.json: |
        {
        "users": [
            {
              "name": "user",
              "password_hash": "E4KaSlT3L4C7gsBJeCoDbl5VFu+60bBNNmBGAU/iGanplQPe",
              "hashing_algorithm": "rabbit_password_hashing_sha256",
              "tags": "administrator"
            }
          ],
          "vhosts": [
            {
              "name": "/"
            }
          ],
          "permissions": [
            {
              "user": "user",
              "vhost": "/",
              "configure": ".*",
              "write": ".*",
              "read": ".*"
            }
          ],
          "queues": [
            {
              "name": "CDL_SCHEMA_SYNCHRO",
              "vhost": "/",
              "durable": true,
              "auto_delete": false,
              "arguments": {
                "x-queue-type": "classic"
              }
            },
            {
              "name": "cdl.data.input",
              "vhost": "/",
              "durable": true,
              "auto_delete": false,
              "arguments": {
                "x-queue-type": "classic"
              }
            },
            {
              "name": "cdl.reports",
              "vhost": "/",
              "durable": true,
              "auto_delete": false,
              "arguments": {
                "x-queue-type": "classic"
              }
            },
            {
              "name": "cdl.document.2.data",
              "vhost": "/",
              "durable": true,
              "auto_delete": false,
              "arguments": {
                "x-queue-type": "classic"
              }
            },
            {
              "name": "cdl.document.data",
              "vhost": "/",
              "durable": true,
              "auto_delete": false,
              "arguments": {
                "x-queue-type": "classic"
              }
            },
            {
              "name": "cdl.timeseries.data",
              "vhost": "/",
              "durable": true,
              "auto_delete": false,
              "arguments": {
                "x-queue-type": "classic"
              }
            },
            {
              "name": "cdl.timeseries2.data",
              "vhost": "/",
              "durable": true,
              "auto_delete": false,
              "arguments": {
                "x-queue-type": "classic"
              }
            }
          ],
          "exchanges": [
            {
              "name": "cdl.data.input",
              "vhost": "/",
              "type": "fanout",
              "durable": true,
              "auto_delete": false,
              "internal": false,
              "arguments": {}
            },
            {
              "name": "cdl.reports",
              "vhost": "/",
              "type": "fanout",
              "durable": true,
              "auto_delete": false,
              "internal": false,
              "arguments": {}
            },
            {
              "name": "CDL_SCHEMA_SYNCHRO",
              "vhost": "/",
              "type": "fanout",
              "durable": true,
              "auto_delete": false,
              "internal": false,
              "arguments": {}
            },
            {
              "name": "cdl.document.data",
              "vhost": "/",
              "type": "topic",
              "durable": true,
              "auto_delete": false,
              "internal": false,
              "arguments": {}
            },
            {
              "name": "cdl.timeseries.data",
              "vhost": "/",
              "type": "topic",
              "durable": true,
              "auto_delete": false,
              "internal": false,
              "arguments": {}
            }
          ],
          "bindings": [
            {
              "source": "cdl.data.input",
              "vhost": "/",
              "destination": "cdl.data.input",
              "destination_type": "queue",
              "routing_key": "",
              "arguments": {}
            },
            {
              "source": "cdl.reports",
              "vhost": "/",
              "destination": "cdl.reports",
              "destination_type": "queue",
              "routing_key": "",
              "arguments": {}
            },
            {
              "source": "CDL_SCHEMA_SYNCHRO",
              "vhost": "/",
              "destination": "CDL_SCHEMA_SYNCHRO",
              "destination_type": "queue",
              "routing_key": "",
              "arguments": {}
            },
            {
              "source": "cdl.document.data",
              "vhost": "/",
              "destination": "cdl.document.data",
              "destination_type": "queue",
              "routing_key": "*.*.*.*.*",
              "arguments": {}
            },
            {
              "source": "cdl.document.data",
              "vhost": "/",
              "destination": "cdl.document.2.data",
              "destination_type": "queue",
              "routing_key": "unordered",
              "arguments": {}
            },
            {
              "source": "cdl.timeseries.data",
              "vhost": "/",
              "destination": "cdl.timeseries.data",
              "destination_type": "queue",
              "routing_key": "*.*.*.*.*",
              "arguments": {}
            },
            {
              "source": "cdl.timeseries.data",
              "vhost": "/",
              "destination": "cdl.timeseries.data",
              "destination_type": "queue",
              "routing_key": "unordered",
              "arguments": {}
            }
          ]
        }
  loadDefinition:
    enabled: true
    existingSecret: load-definition
  extraConfiguration: |
    load_definitions = /app/load_definition.json

kafka:
  replicaCount: 1
  autoCreateTopicsEnable: true
  zookeeper:
    enabled: true

postgresql:
  initdbScriptsConfigMap: infrastructure-postgres-migrations
  postgresqlPassword: CHANGEME
  postgresqlDatabase: CDL
  service:
    type: NodePort
    nodePort: 32000
