global:
  imageRepositoryPath: ""
  imageVersion: latest
  imagePullPolicy: IfNotPresent
  kafkaBrokers:  infrastructure-kafka-headless
  cdlImagePullSecrets: services
  reportTopic: cdl.errors

dataRouter:
  inputTopic: cdl.data.input
  image: cdl-data-router
  bin: data-router

schemaRegistry:
  replicationTopics: cdl.schema.replication
  storageClass: standard
  storageSize: 3Gi
  port: 30150
  image: cdl-schema-registry
  bin: schema-registry

leaderElector:
  heartbeatTime: 2
  image: cdl-leader-elector
  bin: leader-elector


commandService:
  image: cdl-command-service
  bin: command-service

documentStorage:
  image: cdl-document-storage
  bin: document-storage

postgres-document:
  commandServiceReplicaCount: 1
  postgresDbReplicaCount: 1
  postgresConnectionString: "postgres://postgres:CHANGEME@infrastructure-postgresql/CDL"
  postgresUsername: postgres
  postgresPassword: CHANGEME
  postgresHost: infrastructure-postgresql
  postgresPort: 5432
  postgresDbname: CDL
  postgresSchema: public
  ingestionMethod: kafka
  inputTopic: cdl.document.data
  commandService:
    image: cdl-command-service
    bin: command-service

sled-document:
  replicaCommandCount: 1
  replicaDbCount: 1
  maxDbSize: 3Gi
  storageClass: standard
  inputTopic: cdl.document2.data
  documentStorage:
    image: cdl-document-storage
    bin: document-storage
  dataRouter:
    image: cdl-data-router
    bin: data-router
  commandService:
    image: cdl-command-service
    bin: command-service

druid-timeseries:
  replicaCommandCount: 1
  inputTopic: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid
  commandService:
    image: cdl-command-service
    bin: command-service

victoria-metrics-timeseries:
  replicaCommandCount: 1
  inputTopic: cdl.timeseries2.data
  outputURL: http://infrastructure-victoria-metrics-single-server:8428/
  commandService:
    image: cdl-command-service
    bin: command-service
