---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-victoria-metrics-command-service
  labels:
    app: {{ .Release.Name }}-victoria-metrics-command-service
    repository.type: timeseries
    repository.name: victoria-metrics
spec:
  replicas: {{ .Values.replicaCommandCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-victoria-metrics-command-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-victoria-metrics-command-service
        repository.type: timeseries
        repository.name: victoria-metrics
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '51805'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - name: {{ .Release.Name }}-victoria-metrics-command-service
        image: "{{ .Values.global.imageRepositoryPath }}cdl-command-service:{{ .Values.global.imageVersion }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        command: ["/bin/command-service","victoria-metrics"]
        env:
        - name: KAFKA_INPUT_BROKERS
          value: {{ .Values.global.kafkaBrokers }}
        - name: KAFKA_INPUT_GROUP_ID
          value: "cdl-victoria-metrics-command-service"
        - name: KAFKA_INPUT_TOPIC
          value: {{ .Values.inputTopic }}
        - name: VICTORIA_METRICS_OUTPUT_URL
          value: {{ .Values.outputURL }}
        - name: RUST_LOG
          value: "info,command-service=debug"
        - name: REPORT_BROKER
          value: {{ .Values.global.kafkaBrokers }}
        - name: REPORT_TOPIC
          value: {{ .Values.global.reportTopic }}
        - name: INGESTION_METHOD
          value: kafka
        ports:
        - containerPort: 51805
  # TODO: Probes
      imagePullSecrets:
      - name: {{ .Values.global.cdlImagePullSecrets }}

