[package]
name = "schema-registry"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[lib]
name = "schema_registry"
path = "src/lib.rs"

[[bin]]
name = "schema-registry"
path = "src/main.rs"

[dependencies]
# Workspace
utils       = { path = "../utils" }
rpc         = { path = "../rpc" }

# Crates.io
anyhow      = "1.0"
async-trait = "0.1"
chrono      = "0.4"
futures     = "0.3"
indradb-lib = { version = "2.1", features = ["sled-datastore"] }
jmespatch   = "0.3"
jsonschema  = { version = "0.6", default-features = false }
lazy_static = "1.4"
semver      = { version = "0.11", features = ["serde"] }
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
structopt   = "0.3"
thiserror   = "1.0"
tokio       = { version = "1.5", features = ["macros", "rt-multi-thread"] }
tonic       = "0.4"
tracing     = "0.1"
url         = "2.2"
uuid        = { version = "0.8", features = ["v1", "serde"] }
tracing-futures         = "0.2"

[dev-dependencies]
maplit = "1.0.2"
