[package]
name = "schema-registry"
authors = ["CDL Team"]
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

[lib]
name = "schema_registry"
path = "src/lib.rs"

[[bin]]
name = "schema-registry"
path = "src/main.rs"

[dependencies]
# Workspace
rpc         = { path = "../rpc" }
utils       = { path = "../utils" }

# Crates.io
anyhow      = "1.0"
async-trait = "0.1"
jmespatch   = "0.3"
jsonschema  = { version = "0.9", default-features = false }
semver      = { version = "0.11", features = ["serde"] }
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
thiserror   = "1.0"
tokio       = { version = "1.5", features = ["macros", "rt-multi-thread"] }
tonic       = "0.4"
tracing     = "0.1"
url         = "2.2"
uuid        = { version = "0.8", features = ["v4", "serde"] }
sqlx        = { version = "0.5", features = ["runtime-tokio-rustls", "postgres", "sqlite", "macros", "uuid", "json", "offline"] }
tokio-stream            = "0.1"
tracing-futures         = "0.2"

[dev-dependencies]
maplit = "1.0.2"
