global:
  imageRepositoryPath: ""
  imageVersion: latest
  imagePullPolicy: IfNotPresent
  communicationMethod: "kafka"
  kafkaBrokers:  infrastructure-kafka-headless
  cdlImagePullSecrets: services
  reportDestination: cdl.errors
  objectBuilderInput: cdl.materialize
  amqpConnectionString: "amqp://user:CHANGEME@infrastructure-rabbitmq:5672/%2f"

api:
  port: 30152

dataRouter:
  inputSource: cdl.data.input

leaderElector:
  heartbeatTime: 2

queryRouter:
  port: 30153

schemaRegistry:
  port: 30150
  postgresUsername: postgres
  postgresPassword: CHANGEME
  postgresHost: infrastructure-postgresql
  postgresPort: 5432
  postgresDbname: CDL
  postgresSchema: public

edgeRegistry:
  postgresUsername: postgres
  postgresPassword: CHANGEME
  postgresHost: infrastructure-postgresql
  postgresPort: 5432
  postgresDbname: CDL
  postgresSchema: public
  rpcPort: 50110
  consumerTag: edge-registry
  consumerSource: cdl.edge.input

objectBuilder:
  inputPort: 50111

materializerOnDemand:
  inputPort: 50112

webAdmin:
  port: 30151

partialUpdateEngine:
  sleepPhaseLength: 120


postgres-document:
  commandServiceReplicaCount: 1
  queryServiceReplicaCount: 1
  materializerReplicaCount: 1
  postgresConnectionString: "postgres://postgres:CHANGEME@infrastructure-postgresql/CDL"
  postgresUsername: postgres
  postgresPassword: CHANGEME
  postgresHost: infrastructure-postgresql
  postgresPort: 5432
  postgresDbname: CDL
  postgresSchema: public
  inputSource: cdl.document.data

druid-timeseries:
  commandServiceReplicaCount: 1
  queryServiceReplicaCount: 1
  inputSource: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid
  queryURL: http://infrastructure-druid-broker:8082/
  tableName: CDL

victoria-metrics-timeseries:
  commandServiceReplicaCount: 1
  queryServiceReplicaCount: 1
  inputSource: cdl.timeseries2.data
  ingestionMethod: MessageQueue
  outputURL: http://infrastructure-victoria-metrics-single-server:8428/
