global:
  imageRepositoryPath: ""
  imageVersion: latest
  imagePullPolicy: IfNotPresent
  communicationMethod: "kafka"
  kafkaBrokers:  infrastructure-kafka-headless
  cdlImagePullSecrets: services
  reportTopicOrExchange: cdl.errors
  amqpConnectionString: "amqp://user:CHANGEME@infrastructure-rabbitmq:5672/%2f"

dataRouter:
  inputTopicOrQueue: cdl.data.input
  multitasking: true

schemaRegistry:
  storageClass: standard
  storageSize: 3Gi
  port: 30150

leaderElector:
  heartbeatTime: 2

postgres-document:
  commandServiceReplicaCount: 1
  postgresConnectionString: "postgres://postgres:CHANGEME@infrastructure-postgresql/CDL"
  postgresUsername: postgres
  postgresPassword: CHANGEME
  postgresHost: infrastructure-postgresql
  postgresPort: 5432
  postgresDbname: CDL
  postgresSchema: public
  inputTopicOrQueue: cdl.document.data

sled-document:
  replicaCommandCount: 1
  replicaDbCount: 1
  maxDbSize: 3Gi
  storageClass: standard
  inputTopicOrQueue: cdl.document2.data

druid-timeseries:
  replicaCommandCount: 1
  inputTopicOrQueue: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid

victoria-metrics-timeseries:
  replicaCommandCount: 1
  inputTopicOrQueue: cdl.timeseries2.data
  ingestionMethod: MessageQueue
  outputURL: http://infrastructure-victoria-metrics-single-server:8428/
