global:
  imageRepositoryPath: ""
  imageVersion: latest
  imagePullPolicy: IfNotPresent
  communicationMethod: "kafka"
  kafkaBrokers:  infrastructure-kafka-headless
  cdlImagePullSecrets: services
  reportTopicOrExchange: cdl.errors
  amqpConnectionString: "amqp://user:CHANGEME@infrastructure-rabbitmq:5672/%2f"

api:
  port: 30152

dataRouter:
  inputTopicOrQueue: cdl.data.input

leaderElector:
  heartbeatTime: 2

queryRouter:
  port: 30153

schemaRegistry:
  storageClass:
  storageSize: 3Gi
  port: 30150

webAdmin:
  port: 30151

postgres-document:
  commandServiceReplicaCount: 1
  queryServiceReplicaCount: 1
  postgresConnectionString: "postgres://postgres:CHANGEME@infrastructure-postgresql/CDL"
  postgresUsername: postgres
  postgresPassword: CHANGEME
  postgresHost: infrastructure-postgresql
  postgresPort: 5432
  postgresDbname: CDL
  postgresSchema: public
  inputTopicOrQueue: cdl.document.data

druid-timeseries:
  commandServiceReplicaCount: 1
  queryServiceReplicaCount: 1
  inputTopicOrQueue: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid
  queryURL: http://infrastructure-druid-broker:8082/
  tableName: CDL

victoria-metrics-timeseries:
  commandServiceReplicaCount: 1
  queryServiceReplicaCount: 1
  inputTopicOrQueue: cdl.timeseries2.data
  ingestionMethod: MessageQueue
  outputURL: http://infrastructure-victoria-metrics-single-server:8428/
