global:
  imageRepositoryPath: epiphanyplatform/
  imageVersion: master
  imagePullPolicy: Always
  communicationMethod: "kafka"
  kafkaBrokers: 10.1.5.4:9092
  amqpConnectionString: "amqp://rabbitmq:rabbitmq@10.1.1.4:5672/%2f"
  cdlImagePullSecrets: services
  reportTopicOrExchange: cdl.errors

dataRouter:
  inputTopicOrQueue: cdl.data.input
  multitasking: true

schemaRegistry:
  storageClass: standard
  storageSize: 3Gi
  port: 30150

leaderElector:
  heartbeatTime: 2

postgres-document:
  commandServiceReplicaCount: 1
  postgresUsername: postgres
  postgresPassword: postgres
  postgresHost: 10.1.1.5
  postgresPort: 5432
  postgresDbname: cdldb
  postgresSchema: public
  inputTopicOrQueue: cdl.document.data

sled-document:
  replicaCommandCount: 0
  replicaDbCount: 0
  maxDbSize: 3Gi
  storageClass: azurefile
  inputTopicOrQueue: cdl.document2.data

druid-timeseries:
  replicaCommandCount: 1
  inputTopicOrQueue: cdl.timeseries.data
  outputTopic: cdl.timeseries.generic-druid

victoria-metrics-timeseries:
  replicaCommandCount: 1
  inputTopicOrQueue: cdl.timeseries2.data
  outputURL: http://infrastructure-victoria-metrics-single-server:8428/
