input_port = 50106
insert_destination = "cdl.data.input"

[kafka]
group_id = "api"

[notification_consumer]
brokers = "localhost:9092"
group_id = "partial_update_engine"
source = "cdl.reports"

[monitoring]
otel_service_name = "api"

[log]
rust_log = "info,api=debug"
