async_task_limit = 32

[notifications]
enabled = true

[kafka]
group_id = "postgres_command"

[listener]
ordered_sources = "cdl.document.1.data"
unordered_sources = "cdl.document.2.data"

[monitoring]
otel_service_name = "postgres-command"

[log]
rust_log = "info,command_service=debug"
