input_port = 50203
cache_capacity = 1000

[notifications]
enabled = true
destination = "cdl.materialization.reports"

[monitoring]
otel_service_name = "materializer-general"

[log]
rust_log = "info,materializer_general=debug"
