input_port = 50107
schema_registry_url = "https://localhost:50101"
chunk_capacity = 100

[kafka]
group_id = "object_builder"
ingest_topic = "cdl.materialize"

[monitoring]
otel_service_name = "object-builder"

[log]
rust_log = "info,object_builder=debug"
